2021-06-14 09:54:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "CREATE TABLE QUESTION(
Q_ID INT(4) NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(16) NOT NULL,
Q_USER VARCHAR(15),
Q_CONTENT VARCHAR(400) NOT NULL,
Q_CHOICE_A VARCHAR(20) NOT NULL,
Q_CHOICE_B VARCHAR(20) NOT NULL,
Q_DATE DATETIME NOT NULL,
Q_PW INT(4) NOT NULL
PRIMARY KEY([*]Q_ID, USER_ID)
)"; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE QUESTION(
Q_ID INT(4) NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(16) NOT NULL,
Q_USER VARCHAR(15),
Q_CONTENT VARCHAR(400) NOT NULL,
Q_CHOICE_A VARCHAR(20) NOT NULL,
Q_CHOICE_B VARCHAR(20) NOT NULL,
Q_DATE DATETIME NOT NULL,
Q_PW INT(4) NOT NULL
PRIMARY KEY([*]Q_ID, USER_ID)
)"; expected "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE question(
q_id INT(4) NOT NULL AUTO_INCREMENT,
user_id VARCHAR(16) NOT NULL,
q_user VARCHAR(15),
q_content VARCHAR(400) NOT NULL,
q_choice_a VARCHAR(20) NOT NULL,
q_choice_b VARCHAR(20) NOT NULL,
q_date DATETIME NOT NULL,
q_pw INT(4) NOT NULL
PRIMARY KEY(q_id, user_id)
) [42001-200]
2021-06-14 09:55:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "CREATE TABLE QUESTION(
Q_ID INT(4) NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(16) NOT NULL,
Q_USER VARCHAR(15),
Q_CONTENT VARCHAR(400) NOT NULL,
Q_CHOICE_A VARCHAR(20) NOT NULL,
Q_CHOICE_B VARCHAR(20) NOT NULL,
Q_DATE DATETIME,
Q_PW INT(4) NOT NULL
PRIMARY KEY([*]Q_ID, USER_ID)
)"; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE QUESTION(
Q_ID INT(4) NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(16) NOT NULL,
Q_USER VARCHAR(15),
Q_CONTENT VARCHAR(400) NOT NULL,
Q_CHOICE_A VARCHAR(20) NOT NULL,
Q_CHOICE_B VARCHAR(20) NOT NULL,
Q_DATE DATETIME,
Q_PW INT(4) NOT NULL
PRIMARY KEY([*]Q_ID, USER_ID)
)"; expected "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE question(
q_id INT(4) NOT NULL AUTO_INCREMENT,
user_id VARCHAR(16) NOT NULL,
q_user VARCHAR(15),
q_content VARCHAR(400) NOT NULL,
q_choice_a VARCHAR(20) NOT NULL,
q_choice_b VARCHAR(20) NOT NULL,
q_date DATETIME,
q_pw INT(4) NOT NULL
PRIMARY KEY(q_id, user_id)
) [42001-200]
2021-06-14 09:55:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "CREATE TABLE ANSWER(
A_ID INT(4) NOT NULL AUTO_INCREMENT,
Q_ID INT(4) NOT NULL,
USER_ID VARCHAR(16) NOT NULL,
A_ANSWER VARCHAR(1) NOT NULL
PRIMARY KEY([*]A_ID, Q_ID, USER_ID)
)"; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ANSWER(
A_ID INT(4) NOT NULL AUTO_INCREMENT,
Q_ID INT(4) NOT NULL,
USER_ID VARCHAR(16) NOT NULL,
A_ANSWER VARCHAR(1) NOT NULL
PRIMARY KEY([*]A_ID, Q_ID, USER_ID)
)"; expected "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE answer(
a_id INT(4) NOT NULL AUTO_INCREMENT,
q_id INT(4) NOT NULL,
user_id VARCHAR(16) NOT NULL,
a_answer VARCHAR(1) NOT NULL
PRIMARY KEY(a_id, q_id, user_id)
) [42001-200]
2021-06-14 10:06:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE VALUES ""ozeki1998"", ""pw"", ""尾関勝哉"", ""TEST"", ""TEST"", ""男"", ""TEST"", ""TEST"", ""TEST"", '3', ""TEST"", ""TEST"",  ""CURRENT_TIMESTAMP"")[*]"
Syntax error in SQL statement "INSERT INTO PROFILE VALUES ""ozeki1998"", ""pw"", ""尾関勝哉"", ""TEST"", ""TEST"", ""男"", ""TEST"", ""TEST"", ""TEST"", '3', ""TEST"", ""TEST"",  ""CURRENT_TIMESTAMP"")[*]"; SQL statement:
INSERT INTO profile VALUES "ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  "CURRENT_TIMESTAMP") [42000-200]
2021-06-14 10:08:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE VALUES ""ozeki1998"", ""pw"", ""尾関勝哉"", ""TEST"", ""TEST"", ""男"", ""TEST"", ""TEST"", ""TEST"", '3', ""TEST"", ""TEST"",  CURRENT_TIMESTAMP)[*]"
Syntax error in SQL statement "INSERT INTO PROFILE VALUES ""ozeki1998"", ""pw"", ""尾関勝哉"", ""TEST"", ""TEST"", ""男"", ""TEST"", ""TEST"", ""TEST"", '3', ""TEST"", ""TEST"",  CURRENT_TIMESTAMP)[*]"; SQL statement:
INSERT INTO profile VALUES "ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  CURRENT_TIMESTAMP) [42000-200]
2021-06-14 10:09:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO profile VALUES "ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  "CURRENT_TIMESTAMP" [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 10:09:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "ozeki1998" が見つかりません
Column "ozeki1998" not found; SQL statement:
INSERT INTO profile VALUES ("ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  "CURRENT_TIMESTAMP") [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 10:10:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "ozeki1998" が見つかりません
Column "ozeki1998" not found; SQL statement:
INSERT INTO profile VALUES ("ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  CURRENT_TIMESTAMP) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 10:11:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "ozeki1998" が見つかりません
Column "ozeki1998" not found; SQL statement:
INSERT INTO profile VALUES ("ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  CURRENT_TIMESTAMP) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 10:12:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "ozeki1998" が見つかりません
Column "ozeki1998" not found; SQL statement:
INSERT INTO PROFILE VALUES ("ozeki1998", "pw", "尾関勝哉", "TEST", "TEST", "男", "TEST", "TEST", "TEST", '3', "TEST", "TEST",  CURRENT_TIMESTAMP) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 10:17:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT count(*) FROM profile WHERE user_id = ? AND user_pw = ? [42102-199]
2021-06-14 10:17:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT count(*) FROM profile WHERE user_id = ? AND user_pw = ? [42102-199]
2021-06-14 10:17:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT * FROM profile WHERE user_id LIKE ? AND user_pw LIKE ? OR user_name LIKE ? AND user_position LIKE ? AND user_class LIKE ? AND user_gender LIKE ? AND user_major LIKE ? AND user_hobby LIKE ? AND user_personarity LIKE ? AND user_star LIKE ? [42102-199]
2021-06-14 10:19:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT count(*) FROM Profile WHERE user_id = ? AND user_pw = ? [42102-199]
2021-06-14 10:19:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT count(*) FROM Profile WHERE user_id = ? AND user_pw = ? [42102-199]
2021-06-14 10:19:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT * FROM Profile WHERE user_id LIKE ? AND user_pw LIKE ? OR user_name LIKE ? AND user_position LIKE ? AND user_class LIKE ? AND user_gender LIKE ? AND user_major LIKE ? AND user_hobby LIKE ? AND user_personarity LIKE ? AND user_star LIKE ? [42102-199]
2021-06-14 10:20:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PROFILE" が見つかりません
Table "PROFILE" not found; SQL statement:
SELECT * FROM Profile WHERE user_id LIKE ? AND user_pw LIKE ? OR user_name LIKE ? AND user_position LIKE ? AND user_class LIKE ? AND user_gender LIKE ? AND user_major LIKE ? AND user_hobby LIKE ? AND user_personarity LIKE ? AND user_star LIKE ? [42102-199]
2021-06-14 13:44:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO PROFILE VALUES ('null', 'サンプルコース', '3', 'テスト登録文') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 13:45:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO PROFILE VALUES ('null', 'サンプルコース', '3', 'テスト登録文','1111') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 13:46:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO PROFILE VALUES (null, 'サンプルコース', '3', 'テスト登録文','1111') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 13:46:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO PROFILE VALUES (null, 'サンプルコース', '3', 'テスト登録文','1111') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 14:11:55 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.ProfileDAO.select(ProfileDAO.java:26)
	at test.ProfileDAOTest.main(ProfileDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-14 14:19:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "CREATE TABLE ADVICE(
ADV_ID INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
ADV_COURSE VARCHAR(15) NOT NULL,
ADV_YEAR INT(4) NOT NULL,
ADV_CONTENT VARCHAR(400) NOT NULL,
)[*]"; 期待されるステートメント "identifier"
Syntax error in SQL statement "CREATE TABLE ADVICE(
ADV_ID INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
ADV_COURSE VARCHAR(15) NOT NULL,
ADV_YEAR INT(4) NOT NULL,
ADV_CONTENT VARCHAR(400) NOT NULL,
)[*]"; expected "identifier"; SQL statement:
CREATE TABLE advice(
adv_id INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
adv_course VARCHAR(15) NOT NULL,
adv_year INT(4) NOT NULL,
adv_content VARCHAR(400) NOT NULL,
) [42001-200]
2021-06-14 14:20:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO Advice VALUES (null, 'サンプルコース', '3', 'テスト登録文','1111') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 14:21:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: データ変換中にエラーが発生しました "'4ADVICE ' (ADVICE: ""ADV_YEAR"" INT NOT NULL)"
Data conversion error converting "'4ADVICE ' (ADVICE: ""ADV_YEAR"" INT NOT NULL)"; SQL statement:
INSERT INTO Advice VALUES (null, '検索除外用', '4ADVICE ', 'テスト登録文') [22018-200]
2021-06-14 14:25:33 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.ProfileDAO.select(ProfileDAO.java:26)
	at test.ProfileDAOTest.main(ProfileDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-14 14:28:35 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.ProfileDAO.select(ProfileDAO.java:26)
	at test.ProfileDAOTest.main(ProfileDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-14 14:35:52 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.ProfileDAO.select(ProfileDAO.java:26)
	at test.ProfileDAOTest.main(ProfileDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-14 15:28:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM ADVICE QUESTION ANSWER[*]"
Syntax error in SQL statement "SELECT * FROM ADVICE QUESTION ANSWER[*]"; SQL statement:
SELECT * FROM ADVICE QUESTION ANSWER [42000-200]
2021-06-14 15:31:19 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.AdviceDAO.select(AdviceDAO.java:26)
	at test.AdviceDAOTest.main(AdviceDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-14 15:32:43 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.AdviceDAO.select(AdviceDAO.java:26)
	at test.AdviceDAOTest.main(AdviceDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-15 10:58:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_TIMESTAMP" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_TIMESTAMP"; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  'CURRENT_TIMESTAMP', '1111') [22007-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:136)
	at org.h2.value.Value.convertToTimestamp(Value.java:1169)
	at org.h2.value.Value.convertTo(Value.java:822)
	at org.h2.value.Value.convertTo(Value.java:772)
	at org.h2.value.TypeInfo.cast(TypeInfo.java:515)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
	at org.h2.command.dml.Insert.insertRows(Insert.java:187)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: CURRENT_TIMESTAMP
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:166)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:316)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:134)
	... 19 more
2021-06-15 10:59:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_DATETIME" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_DATETIME"; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  'CURRENT_DATETIME', '1111') [22007-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:136)
	at org.h2.value.Value.convertToTimestamp(Value.java:1169)
	at org.h2.value.Value.convertTo(Value.java:822)
	at org.h2.value.Value.convertTo(Value.java:772)
	at org.h2.value.TypeInfo.cast(TypeInfo.java:515)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
	at org.h2.command.dml.Insert.insertRows(Insert.java:187)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: CURRENT_DATETIME
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:166)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:316)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:134)
	... 19 more
2021-06-15 10:59:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  CURRENT_DATETIME, '1111') [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-15 10:59:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  "CURRENT_DATETIME", '1111') [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-15 11:00:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "DATETIME" が見つかりません
Column "DATETIME" not found; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  DATETIME, '1111') [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-15 11:01:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
INSERT INTO question VALUES ('-1', 'ozeki1998', '尾関勝哉', '質問テーブルのサンプルプログラムです。', 'Aに投票', 'Bに投票',  "CURRENT_DATETIME", '1111') [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.command.dml.Insert.prepare(Insert.java:327)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-15 11:31:39 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.QuestionDAO.select(QuestionDAO.java:26)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2021-06-15 11:32:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "#1" がセットされていません
Parameter "#1" is not set; SQL statement:
SELECT * FROM Question WHERE q_id LIKE ? ORDER BY q_id DESC [90012-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.Parameter.checkSet(Parameter.java:94)
	at org.h2.command.Prepared.checkParameters(Prepared.java:180)
	at org.h2.command.CommandContainer.query(CommandContainer.java:144)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.QuestionDAO.select(QuestionDAO.java:37)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:13)
2021-06-15 11:36:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_TIMESTAMP" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_TIMESTAMP"; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
Caused by: java.lang.IllegalArgumentException: CURRENT_TIMESTAMP
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 12 more
2021-06-15 11:36:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:37:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_DATETIME" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_DATETIME"; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
Caused by: java.lang.IllegalArgumentException: CURRENT_DATETIME
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 12 more
2021-06-15 11:37:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:39:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_DATETIME" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_DATETIME"; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
Caused by: java.lang.IllegalArgumentException: CURRENT_DATETIME
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 12 more
2021-06-15 11:39:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:42:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "#7" がセットされていません
Parameter "#7" is not set; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) [90012-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.Parameter.checkSet(Parameter.java:94)
	at org.h2.command.Prepared.checkParameters(Prepared.java:180)
	at org.h2.command.CommandContainer.update(CommandContainer.java:132)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:42:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:44:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "#8" がセットされていません
Parameter "#8" is not set; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) [90012-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.Parameter.checkSet(Parameter.java:94)
	at org.h2.command.Prepared.checkParameters(Prepared.java:180)
	at org.h2.command.CommandContainer.update(CommandContainer.java:132)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:44:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:44:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?) [21002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.insert(QuestionDAO.java:92)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:44:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:45:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?) [21002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.insert(QuestionDAO.java:92)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:45:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:47:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "#8" がセットされていません
Parameter "#8" is not set; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) [90012-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.Parameter.checkSet(Parameter.java:94)
	at org.h2.command.Prepared.checkParameters(Prepared.java:180)
	at org.h2.command.CommandContainer.update(CommandContainer.java:132)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:47:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:48:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: "TIMESTAMP" 定数 "CURRENT_DATETIME" を解析できません
Cannot parse "TIMESTAMP" constant "CURRENT_DATETIME"; SQL statement:
INSERT INTO Question VALUES (?, ?, ?, ?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at dao.QuestionDAO.insert(QuestionDAO.java:136)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
Caused by: java.lang.IllegalArgumentException: CURRENT_DATETIME
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 12 more
2021-06-15 11:48:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 11:59:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "parameterIndex" に対する値 "8" が不正です
Invalid value "8" for parameter "parameterIndex" [90008-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:280)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1573)
	at org.h2.jdbc.JdbcPreparedStatement.setInt(JdbcPreparedStatement.java:407)
	at dao.QuestionDAO.insert(QuestionDAO.java:131)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 11:59:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 13:01:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "parameterIndex" に対する値 "8" が不正です
Invalid value "8" for parameter "parameterIndex" [90008-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:280)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1573)
	at org.h2.jdbc.JdbcPreparedStatement.setInt(JdbcPreparedStatement.java:407)
	at dao.QuestionDAO.insert(QuestionDAO.java:131)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:29)
2021-06-15 13:01:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "CURRENT_DATETIME" が見つかりません
Column "CURRENT_DATETIME" not found; SQL statement:
UPDATE Question SET user_id=?, q_user=?, q_content=?, q_choice_a=?, q_choice_b=?, q_date=CURRENT_DATETIME, q_pw=? WHERE q_id=? [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Update.prepare(Update.java:252)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at dao.QuestionDAO.update(QuestionDAO.java:172)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:41)
2021-06-15 13:10:00 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.QuestionDAO.select(QuestionDAO.java:26)
	at test.QuestionDAOTest.main(QuestionDAOTest.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/B-3/B-3.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
